/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0053DB",
        "on-error-container": "#93000A",
        "surface-container": "#ECEEF0",
        outline: "#737686",
        "outline-variant": "#C3C6D7",
        "secondary-fixed-dim": "#B9C7DF",
        "on-tertiary-container": "#FFEDE6",
        tertiary: "#943700",
        "on-surface-variant": "#434655",
        "on-primary-fixed": "#00174B",
        "tertiary-fixed": "#FFDBCD",
        "on-tertiary-fixed-variant": "#7D2D00",
        "tertiary-fixed-dim": "#FFB596",
        "surface-container-highest": "#E0E3E5",
        "secondary-container": "#D5E3FC",
        "inverse-surface": "#2D3133",
        background: "#F7F9FB",
        "on-tertiary-fixed": "#360F00",
        "on-background": "#191C1E",
        "inverse-on-surface": "#EFF1F3",
        "primary-fixed": "#DBE1FF",
        "tertiary-container": "#BC4800",
        surface: "#F7F9FB",
        primary: "#004AC6",
        "secondary-fixed": "#D5E3FC",
        "inverse-primary": "#B4C5FF",
        "on-secondary": "#FFFFFF",
        "on-primary-container": "#EEEFFF",
        "surface-container-lowest": "#FFFFFF",
        "on-error": "#FFFFFF",
        "on-secondary-fixed": "#0D1C2E",
        "on-secondary-container": "#57657A",
        "on-tertiary": "#FFFFFF",
        "on-primary-fixed-variant": "#003EA8",
        "primary-container": "#2563EB",
        "on-surface": "#191C1E",
        error: "#BA1A1A",
        "error-container": "#FFDAD6",
        "on-secondary-fixed-variant": "#3A485B",
        "primary-fixed-dim": "#B4C5FF",
        "surface-container-high": "#E6E8EA",
        secondary: "#515F74",
        "surface-dim": "#D8DADC",
        "on-primary": "#FFFFFF",
        "surface-variant": "#E0E3E5",
        "surface-bright": "#F7F9FB",
        "surface-container-low": "#F2F4F6",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      boxShadow: {
        ambient: "0 8px 32px rgba(0, 74, 198, 0.08)",
        halo: "0 18px 48px rgba(37, 99, 235, 0.12)",
      },
      backgroundImage: {
        signature: "linear-gradient(135deg, #004AC6 0%, #2563EB 100%)",
        halo: "radial-gradient(circle at top left, rgba(219, 225, 255, 0.95), rgba(247, 249, 251, 0.7) 42%, rgba(242, 244, 246, 1) 100%)",
      },
    },
  },
  plugins: [],
};
